[hooks]
"before:init" = ["git pull origin main"]
"after:bump" = ["git-cliff -o CHANGELOG.md", git add CHANGELOG.md]

[git]
requireBranch = "main"
commitMessage = "chore(release): ${version}"
#changelog = "cz changelog --dry-run --start-rev ${latestTag}"
