[hooks]
"before:init" = ["git pull origin main"]
"after:bump" = ["cz changelog --incremental --unreleased ${version}"]

[git]
requireBranch = "main"
commitMessage = "chore(release): ${version}"
changelog = "cz changelog --dry-run --start-rev ${latestTag}"

[github]
release = true
draft = true
releaseName = "simulat ${version}"