name: return commit message
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - if: "contains(github.event.head_commit.message, 'gh-release')"
        run: echo 'found'
